# Again&Co E-commerce PHP Testing Pipeline
# Test and package your PHP project with comprehensive testing
# Automated testing for all features: Authentication, Cart, Checkout, Admin, etc.

trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: '8.2'
  junitPath: '$(Build.SourcesDirectory)/junit.xml'

steps:
- checkout: self

# Install PHP and required extensions
- script: |
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository ppa:ondrej/php -y
    sudo apt-get update
    sudo apt-get install -y php8.2 php8.2-cli php8.2-xml php8.2-mbstring php8.2-curl php8.2-zip php8.2-sqlite3 php8.2-mysql php8.2-xdebug
    php -v
    php -m | grep -E "(xml|mbstring|curl|zip)"
  displayName: 'Install PHP + extensions'

# Install Composer
- script: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    composer --version
  displayName: 'Install Composer'

# Install project dependencies
- script: composer install --no-interaction --no-progress
  displayName: 'Composer install dependencies'

# Validate PHP syntax in test files
- script: |
    echo "Checking PHP syntax in test files..."
    for file in tests/*.php; do
      if [ -f "$file" ]; then
        echo "Checking $file..."
        php -l "$file" || echo "Syntax error in $file"
      fi
    done
    echo "PHP syntax validation completed"
  displayName: 'Validate PHP Syntax'

# Test PHPUnit setup
- script: |
    echo "Testing PHPUnit setup..."
    php tests/bootstrap.php || echo "Bootstrap file has issues"
    vendor/bin/phpunit --version || echo "PHPUnit version check failed"
    
    # Try to run PHPUnit without any logging first
    echo "Testing basic PHPUnit execution..."
    vendor/bin/phpunit --list-tests || echo "Test discovery failed"
    
    # Try running just the basic test first
    echo "Testing basic test file execution..."
    vendor/bin/phpunit tests/BasicTest.php --verbose || echo "Basic test failed"
    
    # Try running just one existing test file to isolate issues
    echo "Testing existing test file execution..."
    vendor/bin/phpunit tests/FunctionsTest.php --verbose || echo "Functions test file failed"
  displayName: 'Verify PHPUnit Setup'

# Run comprehensive PHPUnit test suite
- script: |
    echo "Running PHPUnit test suite..."
    echo "Current directory: $(pwd)"
    echo "PHP version: $(php --version)"
    echo "Composer version: $(composer --version)"
    
    # Check if vendor/bin/phpunit exists
    if [ -f "vendor/bin/phpunit" ]; then
      echo "PHPUnit found at vendor/bin/phpunit"
      vendor/bin/phpunit --version
    else
      echo "PHPUnit not found in vendor/bin/"
      ls -la vendor/bin/ || echo "vendor/bin directory not found"
      exit 1
    fi
    
    # Create test results directory if it doesn't exist
    mkdir -p $(Build.SourcesDirectory)/test-results
    
    # Check phpunit.xml configuration
    if [ -f "phpunit.xml" ]; then
      echo "PHPUnit configuration found:"
      cat phpunit.xml
    else
      echo "PHPUnit configuration not found"
    fi
    
    # Check test files exist
    echo "Available test files:"
    ls -la tests/*.php || echo "No test files found"
    
    # Run PHPUnit with maximum verbosity and error reporting
    echo "Starting PHPUnit execution..."
    vendor/bin/phpunit --log-junit $(junitPath) --testdox --verbose --debug || {
      echo "PHPUnit failed with exit code $?"
      echo "Checking if partial results were generated..."
      ls -la $(junitPath) || echo "No JUnit file generated"
    }
    
    echo "PHPUnit execution completed."
    echo "Checking for generated files:"
    ls -la *.xml || echo "No XML files found in root"
  displayName: 'Run PHPUnit Test Suite'

# Show test summary
- script: |
    if [ -f "$(junitPath)" ]; then
      echo "=== TEST RESULTS SUMMARY ==="
      echo "JUnit XML file generated successfully"
      echo "File size: $(stat -f%z $(junitPath) 2>/dev/null || stat -c%s $(junitPath) 2>/dev/null || echo 'unknown') bytes"
      echo "File contents preview:"
      head -20 $(junitPath) || echo "Could not read file"
      echo "Check the Tests tab for detailed results"
    else
      echo "Warning: JUnit XML file not found at $(junitPath)"
      echo "Contents of current directory:"
      ls -la
      echo "Contents of test-results directory (if exists):"
      ls -la test-results/ || echo "test-results directory not found"
      
      # Create a minimal JUnit XML file so we have something to publish
      echo "Creating minimal JUnit XML file for reporting..."
      cat > $(junitPath) << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Again&Co E-commerce Tests" tests="1" failures="1" errors="0" time="0">
  <testsuite name="Setup" tests="1" failures="1" errors="0" time="0">
    <testcase name="PHPUnit Execution" classname="Setup">
      <failure message="PHPUnit failed to run or generate results" type="SetupFailure">
        PHPUnit execution failed. Check pipeline logs for details.
      </failure>
    </testcase>
  </testsuite>
</testsuites>
EOF
      echo "Minimal JUnit XML created at $(junitPath)"
    fi
  displayName: 'Display Test Summary'
  condition: always()

# Publish JUnit results to Azure Pipelines Tests tab
- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(junitPath)'
    failTaskOnFailedTests: false
    testRunTitle: 'Again&Co E-commerce Tests'
    publishRunAttachments: true

# Archive test artifacts (only if file exists)
- script: |
    if [ -f "$(junitPath)" ]; then
      echo "JUnit file exists, preparing for archive"
      cp $(junitPath) $(Build.SourcesDirectory)/test-results/
    else
      echo "JUnit file not found, creating empty test results"
      mkdir -p $(Build.SourcesDirectory)/test-results
      echo "No test results generated" > $(Build.SourcesDirectory)/test-results/error.txt
    fi
  displayName: 'Prepare test artifacts'
  condition: always()

- task: PublishBuildArtifacts@1
  displayName: 'Archive test results'
  condition: always()
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/test-results'
    ArtifactName: 'test-results'
    publishLocation: 'Container'
