# Again&Co E-commerce PHP Testing Pipeline
# Test and package your PHP project with comprehensive testing
# Automated testing for all features: Authentication, Cart, Checkout, Admin, etc.

trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: '8.2'
  junitPath: '$(Build.SourcesDirectory)/junit.xml'

steps:
- checkout: self

# Install PHP and required extensions
- script: |
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository ppa:ondrej/php -y
    sudo apt-get update
    sudo apt-get install -y php8.2 php8.2-cli php8.2-xml php8.2-mbstring php8.2-curl php8.2-zip php8.2-sqlite3 php8.2-mysql php8.2-xdebug
    php -v
    php -m | grep -E "(xml|mbstring|curl|zip)"
  displayName: 'Install PHP + extensions'

# Install Composer
- script: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    composer --version
  displayName: 'Install Composer'

# Install project dependencies
- script: composer install --no-interaction --no-progress
  displayName: 'Composer install dependencies'

# Run comprehensive PHPUnit test suite
- script: |
    echo "Running PHPUnit test suite..."
    vendor/bin/phpunit --log-junit $(junitPath) --testdox || true
    echo "PHPUnit execution completed. Check test results below."
  displayName: 'Run PHPUnit Test Suite'

# Show test summary
- script: |
    if [ -f "$(junitPath)" ]; then
      echo "=== TEST RESULTS SUMMARY ==="
      echo "JUnit XML file generated successfully"
      echo "File size: $(stat -f%z $(junitPath) 2>/dev/null || stat -c%s $(junitPath) 2>/dev/null || echo 'unknown') bytes"
      echo "Check the Tests tab for detailed results"
    else
      echo "Warning: JUnit XML file not found"
    fi
  displayName: 'Display Test Summary'
  condition: always()

# Publish JUnit results to Azure Pipelines Tests tab
- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(junitPath)'
    failTaskOnFailedTests: false
    testRunTitle: 'Again&Co E-commerce Tests'
    publishRunAttachments: true

# Archive test artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Archive test results'
  condition: always()
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/junit.xml'
    ArtifactName: 'test-results'
    publishLocation: 'Container'
