# Again&Co E-commerce PHP Testing Pipeline
# Test and package your PHP project with comprehensive testing
# Automated testing for all features: Authentication, Cart, Checkout, Admin, etc.

trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: '8.2'
  junitPath: '$(Build.SourcesDirectory)/junit.xml'
  coveragePath: '$(Build.SourcesDirectory)/coverage.xml'

steps:
- checkout: self

# Install PHP and required extensions
- script: |
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository ppa:ondrej/php -y
    sudo apt-get update
    sudo apt-get install -y php8.2 php8.2-cli php8.2-xml php8.2-mbstring php8.2-curl php8.2-zip php8.2-sqlite3 php8.2-mysql php8.2-xdebug
    php -v
    php -m | grep -E "(xml|mbstring|curl|zip)"
  displayName: 'Install PHP + extensions'

# Install Composer
- script: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    composer --version
  displayName: 'Install Composer'

# Install project dependencies
- script: composer install --no-interaction --no-progress
  displayName: 'Composer install dependencies'

# Run comprehensive PHPUnit test suite
- script: |
    echo "Testing PHPUnit configuration..."
    vendor/bin/phpunit --version
    echo "Validating test configuration..."
    php -l phpunit.xml
    echo "Running test suite..."
    vendor/bin/phpunit --log-junit $(junitPath) --coverage-clover $(coveragePath) --verbose
  displayName: 'Run PHPUnit Test Suite'

# Publish JUnit results to Azure Pipelines Tests tab
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(junitPath)'
    failTaskOnFailedTests: true
    testRunTitle: 'Again&Co E-commerce Tests'

# Publish code coverage results
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(coveragePath)'
    reportDirectory: '$(Build.SourcesDirectory)/coverage'

# Archive test artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Archive test results'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/junit.xml'
    ArtifactName: 'test-results'
    publishLocation: 'Container'
